route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'webhook_receiver'
receivers:
- name: 'webhook_receiver'
  webhook_configs:
  - url: 'http://host.docker.internal:8080/api/monitor'