name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        env:
          MATTERMOST_HOOK_ID: ${{ secrets.MATTERMOST_HOOK_ID }}
          MATTERMOST_SERVER_URL: ${{ secrets.MATTERMOST_SERVER_URL }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t docker.io/your_username/your_image_name:latest \
            --build-arg MATTERMOST_HOOK_ID="${MATTERMOST_HOOK_ID}" \
            --build-arg MATTERMOST_SERVER_URL="${MATTERMOST_SERVER_URL}" \
            --build-arg ALERT_INTERVAL_SECOND="10" \
            .
          docker push docker.io/dogaakcinar/monitoring-check:latest
